export const UPDATE_PAGE_CONTENT = 'UPDATE_PAGE_CONTENT';
export type UPDATE_PAGE_CONTENT = typeof UPDATE_PAGE_CONTENT;

export const UPDATE_LOCAL_USER_AUTHORIZATION = 'UPDATE_LOCAL_USER_AUTHORIZATION';
export type UPDATE_LOCAL_USER_AUTHORIZATION = typeof UPDATE_LOCAL_USER_AUTHORIZATION;