export const UPDATE_PAGE_CONTENT = 'UPDATE_PAGE_CONTENT';
export type UPDATE_PAGE_CONTENT = typeof UPDATE_PAGE_CONTENT;

export const UPDATE_LOCAL_USER_AUTHORIZATION = 'UPDATE_LOCAL_USER_AUTHORIZATION';
export type UPDATE_LOCAL_USER_AUTHORIZATION = typeof UPDATE_LOCAL_USER_AUTHORIZATION;

export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export type UPDATE_FAVORITES = typeof UPDATE_FAVORITES;

export const UPDATE_BASKET = 'UPDATE_BASKET';
export type UPDATE_BASKET = typeof UPDATE_BASKET;

export const ERROR_MSG = 'ERROR_MSG';
export type ERROR_MSG = typeof ERROR_MSG;